const L1_corsiElenco = [
  {
    id: "L1_1_TATONE",
    nome: "Gli Scacchi per Tutti",
    relatore: "Emanuele Tatone",
    aula: "1-II",
    limite: "25",
  },
  {
    id: "L1_5_GUERRERA",
    nome: "Autodifesa",
    relatore: "Maria Guerrera",
    aula: "5-II",
    limite: "25",
  },
  {
    id: "L1_6_SEVERINI",
    nome: "Torneo di Briscola",
    relatore: "Alessandro Severini",
    aula: "6-II",
    limite: "25",
  },
  {
    id: "L1_8_DEVACA",
    nome: "Origami",
    relatore: "Giulio Cabeza de Vaca",
    aula: "8-II",
    limite: "25",
  },
  {
    id: "L1_11_MASCOLI",
    nome: "L'onda di Hokusay",
    relatore: "Matteo Severini",
    aula: "11-II",
    limite: "25",
  },
  {
    id: "L1_14_BUFALINO",
    nome: "Reazione a Catena",
    relatore: "Emma Bufalino",
    aula: "14-II",
    limite: "25",
  },
  {
    id: "L1_15_DELGRECO",
    nome: "Giochi di Carte",
    relatore: "Martina del Greco",
    aula: "15-III",
    limite: "25",
  },
  {
    id: "L1_17_IADELUCA",
    nome: "Corso sul Fumetto",
    relatore: "A. Iadeluca",
    aula: "17-II",
    limite: "25",
  },
  {
    id: "L1_19_BIANCHI",
    nome: "Balli di Gruppo 1",
    relatore: "E. Bianchi",
    aula: "19-III",
    limite: "25",
  },
  {
    id: "L1_21_CIALFI",
    nome: "Corso di Carte",
    relatore: "Rita Cialfi",
    aula: "21-III",
    limite: "25",
  },
  {
    id: "L1_22_CHITTARO",
    nome: "Indovina la Canzone",
    relatore: "Camilla Chittaro",
    aula: "22-III",
    limite: "25",
  },
  {
    id: "L1_27_PREZIUSO",
    nome: "Carte",
    relatore: "Marco delle Ville",
    aula: "27-III",
    limite: "25",
  },
  {
    id: "L1_30_VANNOZZI",
    nome: "Corso di Approfondimento su Shrek",
    relatore: "M. Zarratti",
    aula: "30-IV",
    limite: "25",
  },
  {
    id: "L1_31_BULJUBASIC",
    nome: "Pop Culture",
    relatore: "A. Buljubasic",
    aula: "31-IV",
    limite: "25",
  },
  {
    id: "L1_32_DELLEVILLE",
    nome: "Cubo di Rubik",
    relatore: "Marco delle Ville",
    aula: "32-IV",
    limite: "25",
  },
  {
    id: "L1_34_ZARATTI",
    nome: "Balli di Gruppo 2",
    relatore: "Matilde Zaratti",
    aula: "34-IV",
    limite: "25",
  },
  {
    id: "L1_35_GALIETI",
    nome: "Armocromia e Skincare",
    relatore: "Giada Galieti",
    aula: "35-IV",
    limite: "25",
  },
  {
    id: "L1_39_COVONE",
    nome: "Storia dell'Aviazione Militare Moderna",
    relatore: "Alessandro Covone",
    aula: "39-IV",
    limite: "25",
  },
  {
    id: "L1_40_CASTIGLIANI",
    nome: "Genocidi nel Mondo e nella Storia",
    relatore: "M. Castigliani",
    aula: "40-IV",
    limite: "25",
  },
  {
    id: "L1_45_COTA",
    nome: "Ascoltiamo e non Giudichiamo",
    relatore: "Arianna Cota",
    aula: "45-IV",
    limite: "25",
  },
];

export default L1_corsiElenco;
