const L1_corsiElenco = [
  {
    id: "L1_1_TATONE",
    nome: "Gli Scacchi per Tutti",
    relatore: "Emanuele Tatone",
    aula: "1-II",
    limite: "25",
  },
  {
    id: "L1_5_GUERRERA",
    nome: "Autodifesa",
    relatore: "Maria Guerrera",
    aula: "5-II",
    limite: "25",
  },
  {
    id: "L1_6_SEVERINI",
    nome: "Torneo di Briscola",
    relatore: "Alessandro Severini",
    aula: "6-II",
    limite: "25",
  },
  {
    id: "L1_8_DEVACA",
    nome: "Origami",
    relatore: "Giulio Cabeza de Vaca",
    aula: "8-II",
    limite: "25",
  },
  {
    id: "L1_11_MASCOLI",
    nome: "L'onda di Hokusay",
    relatore: "Matteo Severini",
    aula: "11-II",
    limite: "25",
  },
  {
    id: "L1_14_BUFALINO",
    nome: "Reazione a Catena",
    relatore: "Emma Bufalino",
    aula: "14-II",
    limite: "25",
  },
  {
    id: "L1_15_DELGRECO",
    nome: "Giochi di Carte",
    relatore: "Martina del Greco",
    aula: "15-III",
    limite: "25",
  },
  {
    id: "L1_17_IADELUCA",
    nome: "Corso sul Fumetto",
    relatore: "A. Iadeluca",
    aula: "17-II",
    limite: "25",
  },
  {
    id: "L1_19_BIANCHI",
    nome: "Balli di Gruppo 1",
    relatore: "E. Bianchi",
    aula: "19-III",
    limite: "25",
  },
  {
    id: "L1_21_CIALFI",
    nome: "Corso di Carte",
    relatore: "Rita Cialfi",
    aula: "21-III",
    limite: "25",
  },
  {
    id: "L1_22_CHITTARO",
    nome: "Indovina la Canzone",
    relatore: "Camilla Chittaro",
    aula: "22-III",
    limite: "25",
  },
  {
    id: "L1_27_PREZIUSO",
    nome: "Carte",
    relatore: "Marco delle Ville",
    aula: "27-III",
    limite: "25",
  },
  {
    id: "L1_30_VANNOZZI",
    nome: "Corso di Approfondimento su Shrek",
    relatore: "M. Zarratti",
    aula: "30-IV",
    limite: "25",
  },
  {
    id: "L1_31_BULJUBASIC",
    nome: "Pop Culture",
    relatore: "A. Buljubasic",
    aula: "31-IV",
    limite: "25",
  },
  {
    id: "L1_32_DELLEVILLE",
    nome: "Cubo di Rubik",
    relatore: "Marco delle Ville",
    aula: "32-IV",
    limite: "25",
  },
  {
    id: "L1_34_ZARATTI",
    nome: "Balli di Gruppo 2",
    relatore: "Matilde Zaratti",
    aula: "34-IV",
    limite: "25",
  },
  {
    id: "L1_35_GALIETI",
    nome: "Armocromia e Skincare",
    relatore: "Giada Galieti",
    aula: "35-IV",
    limite: "25",
  },
  {
    id: "L1_39_COVONE",
    nome: "Storia dell'Aviazione Militare Moderna",
    relatore: "Alessandro Covone",
    aula: "39-IV",
    limite: "25",
  },
  {
    id: "L1_40_CASTIGLIANI",
    nome: "Genocidi nel Mondo e nella Storia",
    relatore: "M. Castigliani",
    aula: "40-IV",
    limite: "25",
  },
  {
    id: "L1_45_COTA",
    nome: "Ascoltiamo e non Giudichiamo",
    relatore: "Arianna Cota",
    aula: "45-IV",
    limite: "25",
  },
  {
    id: "L1_INF_MANCINI",
    nome: "Informatica",
    relatore: "Lorenzo Mancini",
    aula: "INF-I",
    limite: "25",
  },
  {
    id: "L1_ASTUDIO_1",
    nome: "Aula Studio 1",
    relatore: "None",
    aula: "10-II",
    limite: "25",
  },
  {
    id: "L1_ASTUDIO_2",
    nome: "Aula Studio 2",
    relatore: "None",
    aula: "26-III",
    limite: "25",
  },
  {
    id: "L1_ASTUDIO_3",
    nome: "Aula Studio 3",
    relatore: "None",
    aula: "33-IV",
    limite: "25",
  },
  {
    id: "L1_ASTUDIO_4",
    nome: "Aula Studio 4",
    relatore: "None",
    aula: "37-IV",
    limite: "25",
  },
];

const L2_corsiElenco = [
  {
    id: "L2_2_BHULLAR",
    nome: "Scacchi 2",
    relatore: "Aish Bhullar",
    aula: "2-II",
    limite: "25",
  },
  {
    id: "L2_3_CERAFOGLI",
    nome: "Analisi I e Problemi da 1MLN$",
    relatore: "Andrea Cerafogli",
    aula: "3-II",
    limite: "25",
  },
  {
    id: "L2_5_GUERRERA",
    nome: "Autodifesa",
    relatore: "Maria Guerrera",
    aula: "5-II",
    limite: "25",
  },
  {
    id: "L2_6_SEVERINI",
    nome: "LIS",
    relatore: "Alessandro Severini",
    aula: "6-II",
    limite: "25",
  },
  {
    id: "L2_7_MASCOLI",
    nome: "LIS",
    relatore: "Alice Mascoli",
    aula: "7-II",
    limite: "25",
  },
  {
    id: "L2_13_AMOROSO",
    nome: "Il Funzionamento dei Motori",
    relatore: "J. Amoroso",
    aula: "13-II",
    limite: "25",
  },
  {
    id: "L2_14_BUFALINO",
    nome: "Reazione a Catena",
    relatore: "Emma Bufalino",
    aula: "14-II",
    limite: "25",
  },
  {
    id: "L2_15_DELGRECO",
    nome: "Giochi di Carte",
    relatore: "Martina del Greco",
    aula: "15-III",
    limite: "25",
  },
  {
    id: "L2_18_CORVI",
    nome: "Barberia",
    relatore: "J. Corvi",
    aula: "18-II",
    limite: "25",
  },
  {
    id: "L2_19_BIANCHI",
    nome: "Balli di Gruppo 1",
    relatore: "E. Bianchi",
    aula: "19-III",
    limite: "25",
  },
  {
    id: "L2_21_CIALFI",
    nome: "Corso di Carte",
    relatore: "Rita Cialfi",
    aula: "21-III",
    limite: "25",
  },
  {
    id: "L2_24_ROMANO",
    nome: "Fight List",
    relatore: "Ludovica Romano",
    aula: "24-III",
    limite: "25",
  },
  {
    id: "L2_35_GALIETI",
    nome: "Armocromia e Skincare",
    relatore: "Giada Galieti",
    aula: "35-IV",
    limite: "25",
  },
  {
    id: "L2_36_CATANIA",
    nome: "Consiglio 101",
    relatore: "Viola Catania",
    aula: "36-IV",
    limite: "25",
  },
  {
    id: "L2_40_CASTIGLIANI",
    nome: "Genicidi nel Mondo e nella Storia",
    relatore: "M. Castigliani",
    aula: "40-IV",
    limite: "25",
  },
  {
    id: "L2_41_POLESI",
    nome: "Teatro",
    relatore: "Matteo Polesi",
    aula: "41-IV",
    limite: "25",
  },
  {
    id: "L2_42_ANDREI",
    nome: "Make it Meme",
    relatore: "E. Andrei",
    aula: "42-IV",
    limite: "25",
  },
  {
    id: "L2_45_COTA",
    nome: "Ascoltiamo e non Giudichiamo",
    relatore: "Arianna Cota",
    aula: "45-IV",
    limite: "25",
  },
  {
    id: "L2_DIS1_GUBBIOTTI",
    nome: "Avanti un Altro",
    relatore: "C. Gubbiotti",
    aula: "DIS1-IV",
    limite: "25",
  },
  {
    id: "L2_ASTUDIO_1",
    nome: "Aula Studio 1",
    relatore: "None",
    aula: "10-II",
    limite: "25",
  },
  {
    id: "L2_ASTUDIO_2",
    nome: "Aula Studio 2",
    relatore: "None",
    aula: "26-III",
    limite: "25",
  },
  {
    id: "L2_ASTUDIO_3",
    nome: "Aula Studio 3",
    relatore: "None",
    aula: "33-IV",
    limite: "25",
  },
  {
    id: "L2_ASTUDIO_4",
    nome: "Aula Studio 4",
    relatore: "None",
    aula: "37-IV",
    limite: "25",
  },
];

const L3_corsiElenco = [
  {
    id: "L3_1_TATONE",
    nome: "Gli Scacchi per Tutti",
    relatore: "Tatone Emanuele",
    aula: "1-II",
    limite: "25",
  },
  {
    id: "L3_6_SEVERINI",
    nome: "Torneo di Briscola",
    relatore: "Alessandro Severini",
    aula: "6-II",
    limite: "25",
  },
  {
    id: "L3_7_STRAMACCIONI",
    nome: "Introduzione a Blender",
    relatore: "Stramaccioni",
    aula: "7-II",
    limite: "25",
  },
  {
    id: "L3_8_DEVACA",
    nome: "Origami",
    relatore: "Giulio Cabeza de Vaca",
    aula: "8-II",
    limite: "25",
  },
  {
    id: "L3_13_AMOROSO",
    nome: "Il funzionamento dei Motori",
    relatore: "J. Amoroso",
    aula: "13-II",
    limite: "25",
  },
  {
    id: "L3_16_DISILVIO",
    nome: "Tecniche di Memoria",
    relatore: "Anita di Silvio",
    aula: "16-III",
    limite: "25",
  },
  {
    id: "L3_18_CORVI",
    nome: "Barberia",
    relatore: "J. Corvi",
    aula: "18-III",
    limite: "25",
  },
  {
    id: "L3_19_BIANCHI",
    nome: "Balli di Gruppo 1",
    relatore: "E. Bianchi",
    aula: "19-III",
    limite: "25",
  },
  {
    id: "L3_20_NERI",
    nome: "Pausa Arte & Artigianato",
    relatore: "G. Neri",
    aula: "20-II",
    limite: "25",
  },
  {
    id: "L3_21_CIALFI",
    nome: "Corso di Carte",
    relatore: "Rita Cialfi",
    aula: "21-III",
    limite: "25",
  },
  {
    id: "L3_22_CHITTARO",
    nome: "Indovina la Canzone",
    relatore: "C. Chittaro",
    aula: "22-III",
    limite: "25",
  },
  {
    id: "L3_23_DACHILLE",
    nome: "La Politica Studentesca da '68 ad Oggi",
    relatore: "Leonardo D'Achille",
    aula: "23-IV",
    limite: "25",
  },
  {
    id: "L3_24_ROMANO",
    nome: "Fight List",
    relatore: "Ludovica Romano",
    aula: "24-III",
    limite: "25",
  },
  {
    id: "L3_27_PREZIUSO",
    nome: "Carte",
    relatore: "L. Preziuso",
    aula: "27-III",
    limite: "25",
  },
  {
    id: "L3_34_ZARATTI",
    nome: "Balli di Gruppo 2",
    relatore: "M. Zaratti",
    aula: "34-IV",
    limite: "25",
  },
  {
    id: "L3_35_GALIETI",
    nome: "Armocromia e Skincare",
    relatore: "Giada Galieti",
    aula: "35-IV",
    limite: "25",
  },
  {
    id: "L3_38_FEDERICI",
    nome: "Chitarra",
    relatore: "E. Federici",
    aula: "38-IV",
    limite: "25",
  },
  {
    id: "L3_41_POLESI",
    nome: "Teatro",
    relatore: "M. Polesi",
    aula: "41-IV",
    limite: "25",
  },
  {
    id: "L3_42_ANDREI",
    nome: "Make It Meme",
    relatore: "E. Andrei",
    aula: "42-IV",
    limite: "25",
  },
  {
    id: "L3_INF_MORIELLO",
    nome: "Programmazione in Phyton",
    relatore: "Davide Moriello",
    aula: "INF-I",
    limite: "25",
  },
  {
    id: "L3_ASTUDIO_1",
    nome: "Aula Studio 1",
    relatore: "None",
    aula: "10-II",
    limite: "25",
  },
  {
    id: "L3_ASTUDIO_2",
    nome: "Aula Studio 2",
    relatore: "None",
    aula: "26-III",
    limite: "25",
  },
  {
    id: "L3_ASTUDIO_3",
    nome: "Aula Studio 3",
    relatore: "None",
    aula: "33-IV",
    limite: "25",
  },
  {
    id: "L3_ASTUDIO_4",
    nome: "Aula Studio 4",
    relatore: "None",
    aula: "37-IV",
    limite: "25",
  },
];

const L4_corsiElenco = [
  {
    id: "L4_2_BHULLAR",
    nome: "Scacchi 2",
    relatore: "Aish Veer Bhullar",
    aula: "2-II",
    limite: "25",
  },
  {
    id: "L4_3_CERAFOGLI",
    nome: "Analisi 1 e Problemi da 1MLN$",
    relatore: "Andrea Cerafogli",
    aula: "3-II",
    limite: "25",
  },
  {
    id: "L4_4_CERASE",
    nome: "Regolamento Calcistico e Arbitraggio",
    relatore: "Francesco Cerase",
    aula: "4-II",
    limite: "25",
  },
  {
    id: "L4_5_GUERRERA",
    nome: "Autodifesa",
    relatore: "M. Guerrara",
    aula: "5-II",
    limite: "25",
  },
  {
    id: "L4_6_SEVERINI",
    nome: "Torneo di Briscola",
    relatore: "Alessandro Severini",
    aula: "6-II",
    limite: "25",
  },
  {
    id: "L4_7_STRAMACCIONI",
    nome: "Introduzione a Blender",
    relatore: "Stramaccioni",
    aula: "7-II",
    limite: "25",
  },
  {
    id: "L4_11_MASCOLI",
    nome: "L'onda di Hokusay",
    relatore: "Stramaccioni",
    aula: "11-II",
    limite: "25",
  },
  {
    id: "L4_12_SEVERINI",
    nome: "Introduzione alla Subacquea",
    relatore: "M. Severini",
    aula: "12-II",
    limite: "25",
  },
  {
    id: "L4_13_AMOROSO",
    nome: "Il Funzionamento dei Motori",
    relatore: "J. moroso",
    aula: "13-II",
    limite: "25",
  },
  {
    id: "L4_16_DISILVIO",
    nome: "Tecniche di Memoria",
    relatore: "Anita di Silvio",
    aula: "16-III",
    limite: "25",
  },
  {
    id: "L4_19_BIANCHI",
    nome: "Balli di Gruppo 1",
    relatore: "E. Bianchi",
    aula: "19-III",
    limite: "25",
  },
  {
    id: "L4_21_CIALFI",
    nome: "Corso di Carte",
    relatore: "R. Cialfi",
    aula: "21-III",
    limite: "25",
  },
  {
    id: "L4_22_CHITTARO",
    nome: "Indovina la Canzone",
    relatore: "C. Chittaro",
    aula: "22-III",
    limite: "25",
  },
  {
    id: "L4_24_ROMANO",
    nome: "Fight List",
    relatore: "Ludovica Romano",
    aula: "24-III",
    limite: "25",
  },
  {
    id: "L4_25_ASCANIO",
    nome: "Chi Vuole Essere Milionario",
    relatore: "M. Ascanio",
    aula: "25-III",
    limite: "25",
  },
  {
    id: "L4_27_PREZIUSO",
    nome: "Carte",
    relatore: "L. Preziuso",
    aula: "27-III",
    limite: "25",
  },
  {
    id: "L4_31_BULJUBASIC",
    nome: "Pop Culture",
    relatore: "A. Buljubasic",
    aula: "31-IV",
    limite: "25",
  },
  {
    id: "L4_34_ZARATTI",
    nome: "Balli di Gruppo 2",
    relatore: "M. Zaratti",
    aula: "42-IV",
    limite: "25",
  },
  {
    id: "L4_41_POLESI",
    nome: "Teatro",
    relatore: "M. Polesi",
    aula: "41-IV",
    limite: "25",
  },
  {
    id: "L4_42_ANDREI",
    nome: "Make it Meme",
    relatore: "E. Andrei",
    aula: "42-IV",
    limite: "25",
  },
  {
    id: "L4_ASTUDIO_1",
    nome: "Aula Studio 1",
    relatore: "None",
    aula: "10-II",
    limite: "25",
  },
  {
    id: "L4_ASTUDIO_2",
    nome: "Aula Studio 2",
    relatore: "None",
    aula: "26-III",
    limite: "25",
  },
  {
    id: "L4_ASTUDIO_3",
    nome: "Aula Studio 3",
    relatore: "None",
    aula: "33-IV",
    limite: "25",
  },
  {
    id: "L4_ASTUDIO_4",
    nome: "Aula Studio 4",
    relatore: "None",
    aula: "37-IV",
    limite: "25",
  },
];

const L5_corsiElenco = [
  {
    id: "L5_4_CERASE",
    nome: "Regolamento Calcistico e Arbitraggio",
    relatore: "Francesco Cerase",
    aula: "4-II",
    limite: "25",
  },
  {
    id: "L5_11_MASCOLI",
    nome: "L'onda di Hokusay",
    relatore: "Alice Mascoli",
    aula: "11-II",
    limite: "25",
  },
  {
    id: "L5_12_SEVERINI",
    nome: "Introduzione alla Subacquea",
    relatore: "Matteo Severini",
    aula: "12-II",
    limite: "25",
  },
  {
    id: "L5_13_AMOROSO",
    nome: "Il funzionamento dei Motori",
    relatore: "Jacopo Amoroso",
    aula: "13-II",
    limite: "25",
  },
  {
    id: "L5_15_DELGRECO",
    nome: "Giochi di Carte",
    relatore: "Martina del Greco",
    aula: "15-III",
    limite: "25",
  },
  {
    id: "L5_16_DISILVIO",
    nome: "Tecniche di Memoria",
    relatore: "Anita di Silvio",
    aula: "16-III",
    limite: "25",
  },
  {
    id: "L5_19_BIANCHI",
    nome: "Balli di Gruppo 1",
    relatore: "Elisabetta Bianchi",
    aula: "19-III",
    limite: "25",
  },
  {
    id: "L5_20_NERI",
    nome: "Pausa Arte & Artigianato",
    relatore: "M. Severini",
    aula: "20-III",
    limite: "25",
  },
  {
    id: "L5_21_CIALFI",
    nome: "Corso di carte",
    relatore: "Rita Cialfi",
    aula: "21-III",
    limite: "25",
  },
  {
    id: "L5_22_CHITTARO",
    nome: "Indovina la Canzone",
    relatore: "Camilla Chittaro",
    aula: "22-III",
    limite: "25",
  },
  {
    id: "L5_23_DACHILLE",
    nome: "La politica studentesca dal '68 ad oggi",
    relatore: "Leonardo D'Achille",
    aula: "23-III",
    limite: "25",
  },
  {
    id: "L5_27_PREZIUSO",
    nome: "Carte",
    relatore: "Leonardo Preziuso",
    aula: "27-III",
    limite: "25",
  },
  {
    id: "L5_28_BAZZOLI",
    nome: "Quiz Pong",
    relatore: "Bianca Bazzoli",
    aula: "28-III",
    limite: "25",
  },
  {
    id: "L5_30_VANNOZZI",
    nome: "Corso di approfondimento su Shrek",
    relatore: "Daria Vannozzi",
    aula: "30-IV",
    limite: "25",
  },
  {
    id: "L5_31_BULJUBASIC",
    nome: "Pop Culture",
    relatore: "Alisa Buljubasic",
    aula: "31-IV",
    limite: "25",
  },
  {
    id: "L5_34_ZARATTI",
    nome: "Balli di Gruppo 2",
    relatore: "Matilde Zaratti",
    aula: "34-IV",
    limite: "25",
  },
  {
    id: "L5_38_FEDERICI",
    nome: "Corso di Chitarra",
    relatore: "Edoardo Federici",
    aula: "38-IV",
    limite: "25",
  },
  {
    id: "L5_41_POLESI",
    nome: "Teatro",
    relatore: "Matteo Polesi",
    aula: "41-IV",
    limite: "25",
  },
  {
    id: "L5_42_ANDREI",
    nome: "Make it Meme",
    relatore: "Elisa Andrei",
    aula: "42-IV",
    limite: "25",
  },
  {
    id: "L5_INF_MANCINI",
    nome: "Informatica",
    relatore: "Lorenzo Mancini",
    aula: "INF-I",
    limite: "25",
  },
  {
    id: "L5_ASTUDIO_1",
    nome: "Aula Studio 1",
    relatore: "None",
    aula: "10-II",
    limite: "25",
  },
  {
    id: "L5_ASTUDIO_2",
    nome: "Aula Studio 2",
    relatore: "None",
    aula: "26-III",
    limite: "25",
  },
  {
    id: "L5_ASTUDIO_3",
    nome: "Aula Studio 3",
    relatore: "None",
    aula: "33-IV",
    limite: "25",
  },
  {
    id: "L5_ASTUDIO_4",
    nome: "Aula Studio 4",
    relatore: "None",
    aula: "37-IV",
    limite: "25",
  },
];

export {
  L1_corsiElenco,
  L2_corsiElenco,
  L3_corsiElenco,
  L4_corsiElenco,
  L5_corsiElenco,
};
